### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by triplesky** [jkenlooper/piecemaker#20]
when i run piecemaker --dir test  --number-of-pieces 100 test.jpg command on mac 
![image](https://user-images.githubusercontent.com/6504772/176134777-fdb65797-0d08-440f-b463-9a16dd88143b.png)

**Comment by jkenlooper** [comment]
The lines.svg file is created by the piecemaker command; it might only have some partial files in that test directory because of previous errors.  Try removing that test directory you created and make a new directory that is empty.  Running the piecemaker script again should recreate the necessary files in the 'test' directory.

The second error is most likely because you don't have the 'optipng' command installed on your machine.  I would recommend using a Linux machine or using the provided Dockerfile to use piecemaker on a Mac or Windows machine.  Otherwise you'll need to make sure you install all the other dependencies that this piecemaker script requires.  See the Docker Usage instructions in the  README.md https://github.com/jkenlooper/piecemaker#docker-usage
