### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Mubashira-Wali** [jkenlooper/piecemaker#6]
for 3 days I am trying to use picemaker but it is generating so many errors, 
(piecemaker --dir test  --number-of-pieces 100 test.jpg) when I run this line it gives an error like no directory name test.

**Comment by jkenlooper** [comment]
@Mubashira-Wali That is most likely because the test directory hasn't been created yet or is not in the current working directory that you are running the piecemaker command.  Try first creating the 'test' directory or changing the option value for --dir to a directory path that you would want the piecemaker to create the files in.  I'd recommend an empty directory for this.

**Comment by Mubashira-Wali** [comment]
I have created the test directory in the current working dir and put a sample image test.jpg in it also but it is still not working.

**Comment by jkenlooper** [comment]
Can you include some more detailed error information about this?  Perhaps the path to the test.jpg that you are using is not right? It doesn't need to be in the 'test' directory that was created.

**Comment by yaqwsx** [comment]
It seems that piecemaker cannot create the output directory itself and also, the directory needs to be empty. PS: Make sure you have svgo installed on your system.

**Comment by yaqwsx** [comment]
@jkenlooper I think you should have included a note that the directory has to be empty in 749630ff8e725da9dcbe1ae98ce605b30d5fe8c0

**Comment by jkenlooper** [comment]
Thank you, I'll update that README to be a little more clear.
