### ISSUE TITLE
Use rsvg instead of Chromium

### ISSUE THREAD

**Issue by drzraf** [jkenlooper/piecemaker#8]
Similar to #1 
Eg: Use https://www.cairographics.org/cookbook/pyrsvg/ instead of a npm package that download pupeeter to control a 135MB Chrome binary...

**Comment by jkenlooper** [comment]
A previous version was using Cairo in order to render the SVG to PNG.  The one feature that was different in how Cairo rendered SVG compared to Chromium was dealing with how the SVG Paths handled scaling the stroke-width.  Specifically the vector-effect attribute and when it is set to non-scaling-stroke.  If I use Cairo the stroke width doesn't correctly implement the non-scaling-stroke like Chromium does resulting in thicker lines.  The thicker lines would then create larger gaps when pixsaw is used to create multiple pieces from that generated graphic.

Now it could be possible to improve pixsaw's algorithm when it is working with thicker lines to avoid creating gaps between the pieces.  Then piecemaker could switch back to using Cairo. 

I think it would be good to also better document why Chromium is being used here instead of the lighter weight library like Cairo.  I'll keep this issue open until then.

**Comment by drzraf** [comment]
Is there a public open issue/pr to track on Cairo bugtracker?

**Comment by jkenlooper** [comment]
https://gitlab.freedesktop.org/cairo/cairo/-/issues
I didn't see anything specific for this minor issue with vector-effect and non-scaling-stroke.

**Comment by jkenlooper** [comment]
Dropped the dependency on Chrome along with svgo in piecemaker version 0.4.3.
